name: "Multievent pipeline workflows" # name of the pipeline

on:
    push: # event- when a push is made to the repository on main branch
        branches:
            - master
            - test
    pull_request:
        branches:
            - master
jobs:
    on-push: # job 1 name
        if: github.event_name== 'push'
        runs-on: ubuntu-latest
        steps: # steps to be executed in the jobs
            - name: "running on master/test push" # step 1
              run: echo "running on master/test push"

    on-pull-request: # job 1 name
        if: github.event_name== 'pull_request'
        runs-on: ubuntu-latest
        steps: # steps to be executed in the jobs
            - name: "running on pull request" # step 1
              run: echo "running on pull request"
    
              