name: print commit message
on:
    push:
        branches:
            - 'master'

jobs:
    print-message:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v6

            - name: print message
              run: 
                echo "commit message:"
                git log -1 --pretty=%B