name: print message
on:
    push:
        branches:
            - 'master'

jobs:
    print-message:
        runs-on: ubuntu-latest

        steps:
            - name: print message
              run: echo "new push detected on main branch"